USE [master]
GO

/****** Object:  Database [ElectronicsStoreDB]    Script Date: 17.01.2026 10:25:54 ******/
CREATE DATABASE [ElectronicsStoreDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ElectronicsStoreDB', FILENAME = N'E:\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\ElectronicsStoreDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ElectronicsStoreDB_log', FILENAME = N'E:\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\ElectronicsStoreDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ElectronicsStoreDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ElectronicsStoreDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ElectronicsStoreDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ElectronicsStoreDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ElectronicsStoreDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ElectronicsStoreDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [ElectronicsStoreDB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [ElectronicsStoreDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ElectronicsStoreDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ElectronicsStoreDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ElectronicsStoreDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ElectronicsStoreDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ElectronicsStoreDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ElectronicsStoreDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ElectronicsStoreDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ElectronicsStoreDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [ElectronicsStoreDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ElectronicsStoreDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ElectronicsStoreDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ElectronicsStoreDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ElectronicsStoreDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ElectronicsStoreDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ElectronicsStoreDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ElectronicsStoreDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ElectronicsStoreDB] SET  MULTI_USER 
GO

ALTER DATABASE [ElectronicsStoreDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ElectronicsStoreDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ElectronicsStoreDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ElectronicsStoreDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ElectronicsStoreDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ElectronicsStoreDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ElectronicsStoreDB] SET QUERY_STORE = ON
GO

ALTER DATABASE [ElectronicsStoreDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [ElectronicsStoreDB] SET  READ_WRITE 
GO


